/*
 * Copyright (c) 2016-2017 MediaTek Inc.
 * Author: Honghui Zhang <honghui.zhang@mediatek.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
#ifndef __DTS_IOMMU_PORT_MT8695_H
#define __DTS_IOMMU_PORT_MT8695_H

#define MTK_M4U_ID(larb, port)		(((larb) << 5) | (port))

#define M4U_LARB0_ID			0
#define M4U_LARB1_ID			1
#define M4U_LARB2_ID			2
#define M4U_LARB3_ID			3
#define M4U_LARB4_ID			4
#define M4U_LARB5_ID			5
#define M4U_LARB6_ID			6
#define M4U_LARB7_ID			7
#define M4U_LARB8_ID			8


/* larb0 VDOUT */
#define M4U_PORT_UHD_OSD		MTK_M4U_ID(M4U_LARB0_ID, 0)
#define M4U_PORT_TVE_OSD		MTK_M4U_ID(M4U_LARB0_ID, 1)

/* larb1 VDEC */
#define M4U_PORT_HW_VDEC_MC_EXT		MTK_M4U_ID(M4U_LARB1_ID, 0)
#define M4U_PORT_HW_VDEC_UFO_EXT	MTK_M4U_ID(M4U_LARB1_ID, 1)
#define M4U_PORT_HW_VDEC_PP_EXT		MTK_M4U_ID(M4U_LARB1_ID, 2)
#define M4U_PORT_HW_VDEC_PRED_RD_EXT	MTK_M4U_ID(M4U_LARB1_ID, 3)
#define M4U_PORT_HW_VDEC_PRED_WR_EXT	MTK_M4U_ID(M4U_LARB1_ID, 4)
#define M4U_PORT_HW_VDEC_PPWRAP_EXT	MTK_M4U_ID(M4U_LARB1_ID, 5)
#define M4U_PORT_HW_VDEC_TILE		MTK_M4U_ID(M4U_LARB1_ID, 6)
#define M4U_PORT_HW_VDEC_VLD_EXT	MTK_M4U_ID(M4U_LARB1_ID, 7)
#define M4U_PORT_HW_VDEC_VLD2_EXT	MTK_M4U_ID(M4U_LARB1_ID, 8)
#define M4U_PORT_HW_VDEC_AVC_MV_EXT	MTK_M4U_ID(M4U_LARB1_ID, 9)
#define M4U_PORT_HW_VDEC_UFO_ENC_EXT	MTK_M4U_ID(M4U_LARB1_ID, 10)

/* larb2 NOT USED */

/* larb3 VENC */
#define M4U_PORT_VENC_RCPU		MTK_M4U_ID(M4U_LARB3_ID, 0)
#define M4U_PORT_VENC_REC_FRM		MTK_M4U_ID(M4U_LARB3_ID, 1)
#define M4U_PORT_VENC_BSDMA		MTK_M4U_ID(M4U_LARB3_ID, 2)
#define M4U_PORT_VENC_SV_COMV		MTK_M4U_ID(M4U_LARB3_ID, 3)
#define M4U_PORT_VENC_RD_COMV		MTK_M4U_ID(M4U_LARB3_ID, 4)
#define M4U_PORT_TS1_DMA_WR		MTK_M4U_ID(M4U_LARB3_ID, 5)
#define M4U_PORT_TS2_DMA_WR		MTK_M4U_ID(M4U_LARB3_ID, 6)
#define M4U_PORT_VENC_CUR_CHROMA	MTK_M4U_ID(M4U_LARB3_ID, 7)
#define M4U_PORT_VENC_REF_CHROMA	MTK_M4U_ID(M4U_LARB3_ID, 8)
#define M4U_PORT_VENC_CUR_LUMA		MTK_M4U_ID(M4U_LARB3_ID, 9)
#define M4U_PORT_VENC_REF_LUMA		MTK_M4U_ID(M4U_LARB3_ID, 10)

/* larb4 VDOUT_2nd_LARB */
#define M4U_PORT_FHD_OSD		MTK_M4U_ID(M4U_LARB4_ID, 0)
#define M4U_PORT_DOLBY_CORE1		MTK_M4U_ID(M4U_LARB4_ID, 1)
#define M4U_PORT_DOLBY_CORE2		MTK_M4U_ID(M4U_LARB4_ID, 2)
#define M4U_PORT_DISP_FAKE		MTK_M4U_ID(M4U_LARB4_ID, 3)
#define M4U_PORT_VIDEO_IN_CH0		MTK_M4U_ID(M4U_LARB4_ID, 4)
#define M4U_PORT_VIDEO_IN_CH1		MTK_M4U_ID(M4U_LARB4_ID, 5)
#define M4U_PORT_VIDEO_IN_CH2		MTK_M4U_ID(M4U_LARB4_ID, 6)

/* larb5 DISP */
#define M4U_PORT_VDO3_UFOD_Y_LENGTH	MTK_M4U_ID(M4U_LARB5_ID, 0)
#define M4U_PORT_VDO3_UFOD_C_LENGTH	MTK_M4U_ID(M4U_LARB5_ID, 1)
#define M4U_PORT_VDO3_UFOD_Y1		MTK_M4U_ID(M4U_LARB5_ID, 2)
#define M4U_PORT_VDO3_UFOD_Y2		MTK_M4U_ID(M4U_LARB5_ID, 3)
#define M4U_PORT_VDO3_UFOD_Y3		MTK_M4U_ID(M4U_LARB5_ID, 4)
#define M4U_PORT_VDO3_UFOD_Y4		MTK_M4U_ID(M4U_LARB5_ID, 5)
#define M4U_PORT_VDO3_UFOD_C1		MTK_M4U_ID(M4U_LARB5_ID, 6)
#define M4U_PORT_VDO3_UFOD_C2		MTK_M4U_ID(M4U_LARB5_ID, 7)
#define M4U_PORT_VDO3_UFOD_C3		MTK_M4U_ID(M4U_LARB5_ID, 8)
#define M4U_PORT_VDO3_UFOD_C4		MTK_M4U_ID(M4U_LARB5_ID, 9)

/* larb6 DISPLAY_2nd_LARB */
#define M4U_PORT_VDO4_UFOD_Y_LENGTH	MTK_M4U_ID(M4U_LARB6_ID, 0)
#define M4U_PORT_VDO4_UFOD_C_LENGTH	MTK_M4U_ID(M4U_LARB6_ID, 1)
#define M4U_PORT_VDO4_UFOD_Y1		MTK_M4U_ID(M4U_LARB6_ID, 2)
#define M4U_PORT_VDO4_UFOD_C1		MTK_M4U_ID(M4U_LARB6_ID, 3)
#define M4U_PORT_VDO4_UFOD_Y2		MTK_M4U_ID(M4U_LARB6_ID, 4)
#define M4U_PORT_VDO4_UFOD_C2		MTK_M4U_ID(M4U_LARB6_ID, 5)
#define M4U_PORT_IMG_UFO_REQ		MTK_M4U_ID(M4U_LARB6_ID, 6)
#define M4U_PORT_IMG_UFO_REQ_CH2	MTK_M4U_ID(M4U_LARB6_ID, 7)
#define M4U_PORT_IMG_RD_REQ		MTK_M4U_ID(M4U_LARB6_ID, 8)
#define M4U_PORT_IMG_RD_REQ_CH2		MTK_M4U_ID(M4U_LARB6_ID, 9)
#define M4U_PORT_IMG_WR_REQ		MTK_M4U_ID(M4U_LARB6_ID, 10)
#define M4U_PORT_IMG_WR_CH2		MTK_M4U_ID(M4U_LARB6_ID, 11)
#define M4U_PORT_IRT_DMA_RW		MTK_M4U_ID(M4U_LARB6_ID, 12)

/* larb7 VDEC */
#define M4U_PORT_VDEC_LAT_VLD_EXT	MTK_M4U_ID(M4U_LARB7_ID, 0)
#define M4U_PORT_VDEC_LAT_VLD2_EXT	MTK_M4U_ID(M4U_LARB7_ID, 1)
#define M4U_PORT_VDEC_LAT_AVC_MV_EXT	MTK_M4U_ID(M4U_LARB7_ID, 2)
#define M4U_PORT_VDEC_LAT_PRED_RD_EXT	MTK_M4U_ID(M4U_LARB7_ID, 3)
#define M4U_PORT_VDEC_LAT_TILE_EXT	MTK_M4U_ID(M4U_LARB7_ID, 4)
#define M4U_PORT_VDEC_LAT_WDMA_EXT	MTK_M4U_ID(M4U_LARB7_ID, 5)

/*
 * larb8 DISP_NR&ROT&DI
 * larb8 only could enable iommu for read/write per larb, could not control
 * iommu enable per hw port.
 */
#define M4U_PORT_IOMMU_READ		MTK_M4U_ID(M4U_LARB8_ID, 0)
#define M4U_PORT_IOMMU_WRITE		MTK_M4U_ID(M4U_LARB8_ID, 1)

#endif
