################################################################################
# Platform Dependent
#
#
################################################################################
obj-$(CONFIG_MTK_FB) += fmt/
obj-$(CONFIG_MTK_FB) += vdout_sys/
obj-$(CONFIG_MTK_FB) += osd/
obj-$(CONFIG_MTK_FB) += vdo/
obj-$(CONFIG_MTK_FB) += p2i/
obj-$(CONFIG_MTK_FB) += pp/
obj-$(CONFIG_MTK_FB) += videoin/
obj-$(CONFIG_MTK_FB) += disp_sys/
obj-$(CONFIG_MTK_FB) += dovi/
