# -----------------------------------------------------------------------------
# Copyright (c) 2011 Ozmo Inc
# Released under the GNU General Public License Version 2 (GPLv2).
# -----------------------------------------------------------------------------

obj-m += ozwpan.o

ozwpan-y += ozmain.o
ozwpan-y += ozpd.o
ozwpan-y += ozusbsvc.o
ozwpan-y += ozusbsvc1.o
ozwpan-y += ozhcd.o
ozwpan-y += ozeltbuf.o
ozwpan-y += ozproto.o
ozwpan-y += ozcdev.o
ozwpan-y += ozkobject.o
ozwpan-y += ozurbparanoia.o
ozwpan-y += oztrace.o

#ccflags-y += -I/repo.new/external/compat-wireless/drivers/net/wireless/usb/ozwpan
#ccflags-y += -Isrc/drivers/net/wireless/usb/ozwpan
#ccflags-y += -I../external/compat-wireless/drivers/net/wireless/usb/ozwpan/bld/src/drivers/net/wireless/usb/ozwpan
