#########################################################
# Bluetooth character device driver
############# 7668 BT sdio Driver
export CONFIG_MTK_COMBO_BT_MT7668_SDIO=m
obj-$(CONFIG_MTK_COMBO_BT_MT7668_SDIO) += btmtksdio.o
btmtksdio-objs     := btmtk_sdio.o btmtk_main.o
