ccflags-y += -I$(srctree)/include/linux/                        \
             -I$(srctree)/include/soc/mediatek/                 \
             -I$(srctree)/drivers/staging/android/mtk_ion/mtk   \
             -I$(srctree)/drivers/staging/android/ion/          \
             -I$(srctree)/drivers/misc/mediatek/sync/           \
             -I$(srctree)/drivers/staging/android               \
             -I$(srctree)/drivers/staging/android/uapi/         \
             -I$(srctree)/include/trustzone/

obj-y += vq_ion.o mtk_vq_mgr.o mtk_vq_debug.o nr_hal.o di_hal.o di_table.o